pipeline:
  mode: test
  abort_on_fail: true

data:
  image_width: 3840
  image_height: 2160
  frames_min: 10
  frames_target: 10
  color_mode: OSC
  bayer_pattern: GBRG
  linear_required: true

normalization:
  enabled: true
  mode: background
  per_channel: true

registration:
  engine: siril
  reference: auto
  output_dir: registered
  registered_filename_pattern: reg_{index:05d}.fit
  min_star_matches: 8
  allow_rotation: true

global_metrics:
  weights:
    background: 0.34
    noise: 0.33
    gradient: 0.33
  clamp: [0.0, 1.0]

tile:
  size_factor: 8
  min_size: 128
  max_divisor: 16
  overlap_fraction: 0.25
  star_min_count: 0

local_metrics:
  clamp: [0.0, 1.0]
  star_mode:
    fwhm_transform: log
    weights:
      fwhm: 0.34
      roundness: 0.33
      contrast: 0.33
  structure_mode:
    metric: energy_over_sigma
    background_weight: 0.5
    metric_weight: 0.5

synthetic:
  frames_min: 5
  frames_max: 5
  clustering:
    mode: state_vector
    vector:
      - global_weight
      - tile_quality_mean
      - tile_quality_variance
      - background
      - noise

reconstruction:
  weighting_function: exponential
  window_function: hanning
  tile_rescale: median_after_background_subtraction

stacking:
  engine: siril
  method: average
  input_dir: registered
  input_pattern: reg_*.fit
  output_file: stacked_average_reference.fits

validation:
  min_fwhm_improvement_percent: 0
  max_background_rms_increase_percent: 0
  min_tile_weight_variance: 0
  require_no_tile_pattern: false

runtime_limits:
  tile_analysis_max_factor_vs_stack: 10
  hard_abort_hours: 12