pipeline:
  mode: production
  abort_on_fail: true

data:
  image_width: 3840
  image_height: 2160
  frames_min: 300
  frames_target: 1000
  color_mode: OSC
  linear_required: true

normalization:
  enabled: true
  mode: background        # background | median
  per_channel: true

registration:
  engine: siril
  reference: auto
  output_dir: registered
  registered_filename_pattern: "reg_{index:05d}.fit"
  min_star_matches: 50
  allow_rotation: true

global_metrics:
  weights:
    background: 0.4
    noise: 0.3
    gradient: 0.3
  clamp: [-3, 3]

tile:
  size_factor: 32
  min_size: 64
  max_divisor: 6
  overlap_fraction: 0.25
  star_min_count: 3

local_metrics:
  clamp: [-3, 3]
  star_mode:
    fwhm_transform: log
    weights:
      fwhm: 0.6
      roundness: 0.2
      contrast: 0.2
  structure_mode:
    metric: energy_over_sigma
    background_weight: 0.3
    metric_weight: 0.7

synthetic:
  frames_min: 15
  frames_max: 30
  clustering:
    mode: state_vector
    vector:
      - global_weight
      - tile_quality_mean
      - tile_quality_variance
      - background
      - noise

reconstruction:
  weighting_function: exponential
  window_function: hanning
  tile_rescale: median_after_background_subtraction

stacking:
  engine: siril
  method: average
  input_dir: synthetic
  input_pattern: "syn_*.fits"
  output_file: stacked.fit

validation:
  min_fwhm_improvement_percent: 5
  max_background_rms_increase_percent: 0
  min_tile_weight_variance: 0.1
  require_no_tile_pattern: true

runtime_limits:
  tile_analysis_max_factor_vs_stack: 3.0
  hard_abort_hours: 6
