pipeline:
  mode: production
  abort_on_fail: true

data:
  image_width: 3840
  image_height: 2160
  frames_min: 800
  frames_target: 1000
  color_mode: OSC
  linear_required: true

registration:
  required: true
  engine: siril                 # siril | relative | wcs_anchor
  reference: auto               # auto | frame_index | path
  output_dir: registered
  registered_filename_pattern: "[abcde]reg_{index:05d}.fit"
  min_star_matches: 50
  allow_rotation: true

global_frame_metrics:
  enabled: true
  background_weight: 0.4
  rms_weight: 0.3
  gradient_weight: 0.3
  min_effective_weight: 0.05   # unter 5 % wird ein Frame praktisch ignoriert

tile_geometry:
  fwhm_scale_factor: 32        # Tile = 32 × mediane FWHM
  tile_min_size: 64
  tile_max_divisor: 6          # min(W,H)/6
  overlap_fraction: 0.25

tile_analysis:
  min_stars_per_tile: 3
  use_star_metrics: true
  use_structure_metrics: true

tile_weights_star:
  fwhm_weight: 0.6
  roundness_weight: 0.2
  contrast_weight: 0.2

tile_weights_structure:
  gradient_weight: 0.5
  rms_weight: 0.25
  background_weight: 0.25

reconstruction:
  synthetic_frames_min: 15
  synthetic_frames_max: 30
  weighting_function: exponential
  window_function: hanning

stacking:
  engine: siril
  method: average
  input_dir: synthetic
  input_pattern: "syn_*.fits"
  output_file: stacked.fit

validation:
  min_fwhm_improvement_percent: 5
  max_background_rms_increase_percent: 0
  min_tile_weight_variance: 0.1

runtime_limits:
  tile_analysis_max_factor_vs_stack: 3.0
  hard_abort_hours: 6
