# FILE: tile_compile.yaml
# PURPOSE
# - User-editable configuration for a Tile-Compile run.
# - This file is validated against tile_compile.schema.json.
# - Values should be aligned with “Methodik v3” (see doc/tile_basierte_qualitatsrekonstruktion_methodik_en.md).
#
# NOTES
# - "assumptions" contains Methodik v3 tolerance thresholds and Reduced Mode behavior.
# - The runner may derive additional input metadata at runtime (image size, frame count, etc.).

pipeline:
  mode: production
  abort_on_fail: true

data:
  image_width: 3840
  image_height: 2160
  frames_min: 50
  color_mode: OSC
  bayer_pattern: GBRG
  linear_required: true

calibration:
  use_bias: false
  use_dark: true
  use_flat: false
  bias_use_master: false
  dark_use_master: true
  flat_use_master: false
  bias_dir: ""
  darks_dir: ""
  flats_dir: ""
  bias_master: ""
  dark_master: ""
  flat_master: ""
  pattern: "*.fit*"

assumptions:
  frames_min: 50
  frames_optimal: 200
  frames_reduced_threshold: 199
  exposure_time_tolerance_percent: 5.0
  registration_residual_warn_px: 0.5
  registration_residual_max_px: 1.0
  elongation_warn: 0.3
  elongation_max: 0.4
  tracking_error_max_px: 1.0
  reduced_mode_skip_clustering: true
  reduced_mode_cluster_range: [5, 10]

normalization:
  enabled: true
  mode: background        # background | median
  per_channel: true

registration:
  engine: opencv_cfa
  reference: auto
  allow_rotation: true   
  min_star_matches: 20   
  output_dir: registered
  registered_filename_pattern: "reg_{index:05d}.fit"

tile_denoising:
  enabled: true
  kernel_size: 31
  alpha: 1.5

global_metrics:
  weights:
    background: 0.4
    noise: 0.3
    gradient: 0.3
  clamp: [-3, 3]

tile:
  size_factor: 32
  min_size: 64
  max_divisor: 6
  overlap_fraction: 0.25
  star_min_count: 3

local_metrics:
  clamp: [-3, 3]
  star_mode:
    # FWHM, roundness und contrast werden gemäß Methodik v3.1 MAD-normalisiert;
    # es gibt kein log-Transform mehr. Die Gewichte definieren direkt die
    # Kombination Q_star = w_fwhm·(-FWHM̃) + w_round·R̃ + w_con·C̃.
    weights:
      fwhm: 0.6
      roundness: 0.2
      contrast: 0.2
  structure_mode:
    # Strukturmodus nutzt ENR = E/σ und lokalen Hintergrund B_local:
    #   Q_struct = metric_weight·ENR̃ − background_weight·B̃_local
    background_weight: 0.3
    metric_weight: 0.7

synthetic:
  weighting: tile_weighted
  frames_min: 15
  frames_max: 30
  clustering:
    mode: state_vector
    vector:
      - global_weight
      - tile_quality_mean
      - tile_quality_variance
      - background
      - noise

reconstruction:
  weighting_function: exponential
  window_function: hanning
  tile_rescale: median_after_background_subtraction

debayer: true

stacking:
  method: rej
  # Default: stack synthetic RGB frames (syn_*.fits) produced in SYNTHETIC_FRAMES.
  # In reduced mode or when no synthetic frames exist, the pipeline falls back
  # to reconstructed_* channels automatically.
  input_dir: synthetic
  input_pattern: "syn_*.fits"
  output_file: stacked.fit
  sigma_clip:
    sigma_low: 3
    sigma_high: 3
    max_iters: 3
    min_fraction: 0.5

validation:
  min_fwhm_improvement_percent: 5
  max_background_rms_increase_percent: 0
  min_tile_weight_variance: 0.1
  require_no_tile_pattern: true

runtime_limits:
  tile_analysis_max_factor_vs_stack: 3.0
  hard_abort_hours: 6
