# FILE: tile_compile.schema.yaml
# PURPOSE
# - Human-oriented schema for tile_compile.yaml.
# - Used as a basis for GUI/editor presentation (field types, editability, defaults, descriptions).
# - Complements tile_compile.schema.json (machine-readable validation).
# - Separates auto-derived input metadata (non-editable) from explicitly configurable Methodik parameters.
#
# SCOPE
# - This file is documentation/editor metadata.
# - The authoritative machine validation is tile_compile.schema.json + backend cross-field checks.
#
# Aligned with: Methodik v3 (doc/tile_basierte_qualitatsrekonstruktion_methodik_en.md)

schema_version: 3

# ============================================================
# PIPELINE
# ============================================================

pipeline:
  mode:
    type: enum
    values: [production, test]
    required: true
    editable: true

  abort_on_fail:
    type: boolean
    required: true
    editable: true

# ============================================================
# INPUT / DATEN (automatisch ermittelt)
# Diese Felder werden aus dem Input-Verzeichnis bzw. FITS-
# Headern gelesen und sind NICHT editierbar.
# ============================================================

input:
  image_width:
    type: integer
    source: fits_header
    editable: false
    description: "NAXIS1 – Bildbreite in Pixeln"

  image_height:
    type: integer
    source: fits_header
    editable: false
    description: "NAXIS2 – Bildhöhe in Pixeln"

  frames_detected:
    type: integer
    source: filesystem
    editable: false
    description: "Anzahl erkannter FITS-Dateien"

  color_mode:
    type: enum
    values: [OSC, MONO]
    source: fits_header
    editable: confirm
    description: "Aus FITS abgeleitet, vor Run bestätigbar"

  bayer_pattern:
    type: enum
    values: [RGGB, BGGR, GBRG, GRBG]
    source: fits_header
    editable: confirm
    default: GBRG
    description: "BAYERPAT (Bayer-Muster) für OSC/CFA; wird für Debayer verwendet"

# ============================================================
# ASSUMPTIONS (Methodik v3 §2)
# Hard, Soft, and Implicit assumptions with tolerances
# ============================================================

assumptions:
  frames_min:
    type: integer
    min: 1
    default: 50
    required: false
    editable: true
    description: "Hard minimum frame count. Below this: abort."

  frames_optimal:
    type: integer
    min: 1
    default: 800
    required: false
    editable: true
    description: "Optimal frame count for full methodology."

  frames_reduced_threshold:
    type: integer
    min: 1
    default: 200
    required: false
    editable: true
    description: "Below this (but above frames_min): reduced mode."

  exposure_time_tolerance_percent:
    type: number
    min: 0
    max: 100
    default: 5
    required: false
    editable: true
    description: "Maximum allowed deviation in exposure time (Hard assumption)."

  registration_residual_warn_px:
    type: number
    min: 0
    default: 0.5
    required: false
    editable: true
    description: "Registration residual threshold for warning."

  registration_residual_max_px:
    type: number
    min: 0
    default: 1.0
    required: false
    editable: true
    description: "Maximum allowed registration residual. Above this: abort."

  elongation_warn:
    type: number
    min: 0
    max: 1
    default: 0.3
    required: false
    editable: true
    description: "Star elongation threshold for warning."

  elongation_max:
    type: number
    min: 0
    max: 1
    default: 0.4
    required: false
    editable: true
    description: "Maximum allowed star elongation. Above this: abort."

  tracking_error_max_px:
    type: number
    min: 0
    default: 1.0
    required: false
    editable: true
    description: "Maximum allowed tracking error per exposure in pixels (implicit assumption from Methodik v3 §1.3)."

  reduced_mode_skip_clustering:
    type: boolean
    default: true
    required: false
    editable: true
    description: "Skip STATE_CLUSTERING and SYNTHETIC_FRAMES in reduced mode."

  reduced_mode_cluster_range:
    type: array
    length: 2
    items: integer
    default: [5, 10]
    required: false
    editable: true
    description: "Cluster count range for reduced mode (if not skipped)."

# ============================================================
# NORMALISIERUNG (Pflicht, Methodik-Zwang)
# Methodik v3 §4
# ============================================================

normalization:
  enabled:
    type: boolean
    const: true
    editable: false
    description: "Mandatory: must be true per Methodik v3"

  mode:
    type: enum
    values: [background, median]
    required: true
    editable: true

  per_channel:
    type: boolean
    required: true
    editable: true

# ============================================================
# REGISTRIERUNG
# Methodik v3 §3 (Phase 1)
# ============================================================

registration:
  engine:
    type: enum
    values: [siril]
    required: true
    editable: true

  reference:
    type: enum
    values: [auto]
    required: true
    editable: true

  output_dir:
    type: string
    required: true
    editable: true

  registered_filename_pattern:
    type: string
    required: true
    editable: true

  min_star_matches:
    type: integer
    min: 1
    required: true
    editable: true

  allow_rotation:
    type: boolean
    required: true
    editable: true

  siril_script:
    type: string
    required: false
    editable: true
    description: "Custom Siril script path (empty = use default)"

# ============================================================
# GLOBALE FRAME-METRIKEN
# Methodik v3 §5
# ============================================================

global_metrics:
  weights:
    background:
      type: number
      min: 0
      max: 1
      required: true
      editable: true
      description: "Weight α for background metric"

    noise:
      type: number
      min: 0
      max: 1
      required: true
      editable: true
      description: "Weight β for noise metric"

    gradient:
      type: number
      min: 0
      max: 1
      required: true
      editable: true
      description: "Weight γ for gradient metric"

    _constraint: "α + β + γ = 1.0 (enforced by backend)"

  clamp:
    type: array
    length: 2
    items: number
    default: [-3, 3]
    required: true
    editable: true
    description: "Clamp range for Q_f"

# ============================================================
# TILE-GEOMETRIE (seeing-adaptiv)
# Methodik v3 §6
# ============================================================

tile:
  size_factor:
    type: integer
    min: 1
    default: 32
    required: true
    editable: true
    description: "Factor s: T_0 = s · FWHM"

  min_size:
    type: integer
    min: 1
    default: 64
    required: true
    editable: true
    description: "Minimum tile size T_min"

  max_divisor:
    type: integer
    min: 1
    default: 6
    required: true
    editable: true
    description: "Maximum divisor D: T_max = min(W,H) / D"

  overlap_fraction:
    type: number
    min: 0
    max: 0.5
    default: 0.25
    required: true
    editable: true
    description: "Overlap fraction o: O = o · T"

  star_min_count:
    type: integer
    min: 0
    default: 3
    required: true
    editable: true
    description: "Minimum stars for star-based local metrics"

# ============================================================
# LOKALE METRIKEN
# Methodik v3 §7
# ============================================================

local_metrics:
  clamp:
    type: array
    length: 2
    items: number
    default: [-3, 3]
    required: true
    editable: true
    description: "Clamp range for Q_local"

  star_mode:
    fwhm_transform:
      type: enum
      values: [log]
      const: log
      editable: false
      description: "Mandatory: log transform per Methodik v3"

    weights:
      fwhm:
        type: number
        min: 0
        max: 1
        default: 0.6
        required: true
        editable: true

      roundness:
        type: number
        min: 0
        max: 1
        default: 0.2
        required: true
        editable: true

      contrast:
        type: number
        min: 0
        max: 1
        default: 0.2
        required: true
        editable: true

      _constraint: "fwhm + roundness + contrast = 1.0 (enforced by backend)"

  structure_mode:
    metric:
      type: enum
      values: [energy_over_sigma]
      const: energy_over_sigma
      editable: false
      description: "Mandatory: E/σ metric per Methodik v3"

    background_weight:
      type: number
      min: 0
      max: 1
      default: 0.3
      required: true
      editable: true

    metric_weight:
      type: number
      min: 0
      max: 1
      default: 0.7
      required: true
      editable: true

    _constraint: "background_weight + metric_weight = 1.0 (enforced by backend)"

# ============================================================
# SYNTHETISCHE FRAMES / CLUSTERING
# Methodik v3 §10
# ============================================================

synthetic:
  frames_min:
    type: integer
    min: 1
    default: 15
    required: true
    editable: true
    description: "Minimum synthetic frames (k_min)"

  frames_max:
    type: integer
    min: 1
    default: 30
    required: true
    editable: true
    description: "Maximum synthetic frames (k_max)"

  clustering:
    mode:
      type: enum
      values: [state_vector]
      const: state_vector
      editable: false

    k_selection:
      type: enum
      values: [silhouette_auto]
      default: silhouette_auto
      editable: false
      description: "Automatic k selection via silhouette score"

    cluster_count_range:
      type: array
      length: 2
      items: integer
      default: [15, 30]
      required: true
      editable: true
      description: "Allowed k range for clustering"

    vector:
      type: array
      items: enum
      values:
        - global_weight
        - tile_quality_mean
        - tile_quality_variance
        - background
        - noise
      required: true
      editable: true
      description: "State vector components"

# ============================================================
# REKONSTRUKTION
# Methodik v3 §9
# ============================================================

reconstruction:
  weighting_function:
    type: enum
    values: [exponential]
    const: exponential
    editable: false
    description: "Mandatory: exponential weighting per Methodik v3"

  window_function:
    type: enum
    values: [hanning]
    const: hanning
    editable: false
    description: "Mandatory: Hanning window per Methodik v3"

  tile_rescale:
    type: enum
    values: [median_after_background_subtraction]
    const: median_after_background_subtraction
    editable: false
    description: "Mandatory: median rescale after background subtraction"

# ============================================================
# STACKING
# Methodik v3 §11
# ============================================================

stacking:
  engine:
    type: enum
    values: [siril]
    required: true
    editable: true

  method:
    type: enum
    values: [average, rej]
    default: rej
    required: true
    editable: true
    description: "Stacking method: average = plain linear mean; rej = sigma-clipping rejection then linear mean"

  input_dir:
    type: string
    required: true
    editable: true

  input_pattern:
    type: string
    required: true
    editable: true

  output_file:
    type: string
    required: true
    editable: true

  siril_script:
    type: string
    required: false
    editable: true
    description: "Custom Siril script path (empty = use default)"

# ============================================================
# VALIDIERUNG
# Methodik v3 §12
# ============================================================

validation:
  min_fwhm_improvement_percent:
    type: number
    min: 0
    default: 5
    required: true
    editable: true

  max_background_rms_increase_percent:
    type: number
    min: 0
    default: 0
    required: true
    editable: true

  min_tile_weight_variance:
    type: number
    min: 0
    default: 0.1
    required: true
    editable: true

  require_no_tile_pattern:
    type: boolean
    default: true
    required: true
    editable: true

# ============================================================
# RUNTIME LIMITS
# ============================================================

runtime_limits:
  tile_analysis_max_factor_vs_stack:
    type: number
    min: 0
    default: 3.0
    required: true
    editable: true

  hard_abort_hours:
    type: number
    min: 0
    default: 6
    required: true
    editable: true
