import { el } from "../utils/dom.js";
import { t } from "../i18n/i18n.js";
import { api } from "../api/client.js";
import { API_ENDPOINTS } from "../api/endpoints.js";

const SPECS = {
  num_sample_points:{value:0,min:0,max:3000,step:10}, poly_degree:{value:2,min:1,max:6,step:1},
  rbf_smooth:{value:2,min:0,max:10,step:.05}, downsample_scale:{value:4,min:1,max:8,step:1},
  patch_size:{value:35,min:3,max:101,step:2,odd:true}, patch_estimator:{value:"sigma_clipped_median",options:["median","sigma_clipped_median"]},
  stretch_mode:{value:"linear",options:["none","linear","mtf"]}, stretch_target_median:{value:.25,min:.01,max:.99,step:.01},
  border_margin:{value:10,min:0,max:250,step:1}, bright_exclusion_fraction:{value:.2,min:.01,max:.99,step:.01},
  gradient_descent_max_iters:{value:100,min:1,max:500,step:1}, random_seed:{value:42,min:-2147483648,max:2147483647,step:1},
  normalize_between_stages:{value:true}, apply_guards:{value:true}, mono_mode:{value:"rgb_duplicate",options:["rgb_duplicate","disabled"]},
};

function scalar(raw,fallback){const v=String(raw??"").trim().replace(/\s+#.*$/,"");if(typeof fallback==="boolean")return v==="true"?true:v==="false"?false:fallback;if(typeof fallback==="number"){const n=Number(v);return Number.isFinite(n)?n:fallback;}return v.replace(/^['"]|['"]$/g,"")||fallback;}
function block(lines,name,start=0,indent=0){const re=new RegExp(`^${" ".repeat(indent)}${name}:\\s*(?:#.*)?$`);const s=lines.findIndex((line,i)=>i>=start&&re.test(line));if(s<0)return null;let e=s+1;while(e<lines.length&&(lines[e].trim()===""||lines[e].match(/^\s*/)[0].length>indent))e++;return{s,e};}
export function readBgeYaml(yaml){const lines=String(yaml||"").split(/\r?\n/),out={};const b=block(lines,"bge",0,0),a=b&&block(lines,"autobge",b.s+1,2);for(const[key,spec]of Object.entries(SPECS)){const fallback=spec.value;const found=a&&lines.slice(a.s+1,a.e).find(line=>new RegExp(`^\\s{4}${key}:`).test(line));out[key]=found?scalar(found.replace(new RegExp(`^\\s{4}${key}:\\s*`),""),fallback):fallback;}out.method=b?(lines.slice(b.s+1,b.e).find(line=>/^\s{2}method:/.test(line))||"").replace(/^\s{2}method:\s*/,"").trim():"none";out.exclusion_polygons=[];if(a){const p=lines.findIndex((line,i)=>i>a.s&&i<a.e&&/^\s{4}exclusion_polygons:/.test(line));if(p>=0&&!/\[\s*\]\s*$/.test(lines[p])){let current=null;for(let i=p+1;i<a.e;i++){if(/^\s{6}-\s*$/.test(lines[i])){current=[];out.exclusion_polygons.push(current);continue;}const m=lines[i].match(/^\s{8}-\s*\[\s*([-+0-9.eE]+)\s*,\s*([-+0-9.eE]+)\s*\]/);if(m&&current)current.push([Number(m[1]),Number(m[2])]);else if(lines[i].trim()&&!/^\s{6,}/.test(lines[i]))break;}out.exclusion_polygons=out.exclusion_polygons.filter(poly=>poly.length>=3);}}return out;}
function yv(v){return typeof v==="boolean"?(v?"true":"false"):String(v);}
export function patchBgeYaml(yaml,params,polygons){const lines=String(yaml||"").split(/\r?\n/);let b=block(lines,"bge",0,0);if(!b){if(lines.at(-1)!=="")lines.push("");lines.push("bge:");b={s:lines.length-1,e:lines.length};}let method=lines.findIndex((line,i)=>i>b.s&&i<b.e&&/^\s{2}method:/.test(line));if(method<0){lines.splice(b.s+1,0,"  method: autobge");method=b.s+1;}else lines[method]="  method: autobge";b=block(lines,"bge",0,0);let a=block(lines,"autobge",b.s+1,2);if(!a){lines.splice(b.e,0,"  autobge:");a={s:b.e,e:b.e+1};}for(const[key,value]of Object.entries(params)){let i=lines.findIndex((line,n)=>n>a.s&&n<a.e&&new RegExp(`^\\s{4}${key}:`).test(line));if(i<0){lines.splice(a.e,0,`    ${key}: ${yv(value)}`);a.e++;}else lines[i]=`    ${key}: ${yv(value)}`;}
  let p=lines.findIndex((line,n)=>n>a.s&&n<a.e&&/^\s{4}exclusion_polygons:/.test(line));if(p>=0){let end=p+1;while(end<lines.length&&(lines[end].trim()===""||/^\s{6,}/.test(lines[end])))end++;lines.splice(p,end-p);a.e-=end-p;}
  const polyLines=["    exclusion_polygons:"];if(!polygons.length)polyLines[0]+=" []";else for(const poly of polygons){polyLines.push("      -");for(const [x,y]of poly)polyLines.push(`        - [${x.toFixed(6)}, ${y.toFixed(6)}]`);}lines.splice(a.e,0,...polyLines);return lines.join("\n");}

export function openBgePreview({runId,runDir,yaml,onApply}){
  const initial=readBgeYaml(yaml),controls={},initialPolygons=initial.exclusion_polygons.map(poly=>poly.map(point=>[...point])),polygons=initial.exclusion_polygons.map(poly=>poly.map(point=>[...point])),pending=[];let image=null,diag=null,view="corrected",scale=1,ox=0,oy=0,drag=false,lx=0,ly=0,drawMode=false,generation=0,controller=null,timer=null;
  const canvas=el("canvas",{width:900,height:600,style:"width:100%;height:min(62vh,600px);background:#05070a;cursor:grab"});
  const hist=el("canvas",{width:256,height:90,style:"width:256px;height:90px;background:#0b1020;border:1px solid var(--tc-border-color,#334155)"});
  const status=el("div",{class:"tc-text-sm",style:"min-height:1.5em;color:var(--tc-danger,#ef4444)"},t("ui.message.bge_loading","Calculating BGE preview…"));
  const info=el("div",{class:"tc-text-sm tc-mono"},"");
  function draw(){const c=canvas.getContext("2d");c.clearRect(0,0,canvas.width,canvas.height);if(!image)return;c.drawImage(image,ox,oy,image.width*scale,image.height*scale);const point=(x,y,color,r=3)=>{c.fillStyle=color;c.beginPath();c.arc(ox+x*image.width*scale,oy+y*image.height*scale,r,0,Math.PI*2);c.fill();};if(diag)for(const p of diag.sample_points||[])point(p.x,p.y,p.channel==="R"?"#ef4444":p.channel==="G"?"#22c55e":"#3b82f6",2);c.lineWidth=2;c.strokeStyle="#ef4444";c.fillStyle="rgba(239,68,68,.18)";for(const poly of [...polygons,pending]){if(!poly.length)continue;c.beginPath();poly.forEach(([x,y],i)=>{const px=ox+x*image.width*scale,py=oy+y*image.height*scale;i?c.lineTo(px,py):c.moveTo(px,py);});if(poly!==pending)c.closePath();c.fill();c.stroke();}}
  function fit(){if(!image)return;scale=Math.min(canvas.width/image.width,canvas.height/image.height);ox=(canvas.width-image.width*scale)/2;oy=(canvas.height-image.height*scale)/2;draw();}
  function updateHistogram(){if(!image)return;const tmp=document.createElement("canvas");tmp.width=image.width;tmp.height=image.height;const c=tmp.getContext("2d",{willReadFrequently:true});c.drawImage(image,0,0);const data=c.getImageData(0,0,tmp.width,tmp.height).data,bins=[new Uint32Array(256),new Uint32Array(256),new Uint32Array(256)];for(let i=0;i<data.length;i+=4){bins[0][data[i]]++;bins[1][data[i+1]]++;bins[2][data[i+2]]++;}const out=hist.getContext("2d"),max=Math.max(1,...bins.flatMap(b=>Array.from(b.slice(1,255))));out.clearRect(0,0,hist.width,hist.height);["#ef4444","#22c55e","#3b82f6"].forEach((color,ch)=>{out.strokeStyle=color;out.globalAlpha=.8;out.beginPath();for(let x=0;x<256;x++){const y=hist.height-Math.log1p(bins[ch][x])/Math.log1p(max)*hist.height;x?out.lineTo(x,y):out.moveTo(x,y);}out.stroke();});out.globalAlpha=1;}
  function xy(e){const r=canvas.getBoundingClientRect(),cx=(e.clientX-r.left)*canvas.width/r.width,cy=(e.clientY-r.top)*canvas.height/r.height;return[(cx-ox)/(image.width*scale),(cy-oy)/(image.height*scale)];}
  canvas.addEventListener("pointerdown",e=>{if(drawMode&&image){const[x,y]=xy(e);if(x>=0&&x<=1&&y>=0&&y<=1){pending.push([x,y]);draw();}return;}drag=true;lx=e.clientX;ly=e.clientY;canvas.setPointerCapture(e.pointerId);});
  canvas.addEventListener("pointermove",e=>{if(!drag)return;const r=canvas.getBoundingClientRect();ox+=(e.clientX-lx)*canvas.width/r.width;oy+=(e.clientY-ly)*canvas.height/r.height;lx=e.clientX;ly=e.clientY;draw();});canvas.addEventListener("pointerup",()=>drag=false);
  canvas.addEventListener("dblclick",e=>{e.preventDefault();if(drawMode&&pending.length>=3){polygons.push(pending.splice(0));drawMode=false;draw();schedule();}else fit();});
  canvas.addEventListener("wheel",e=>{e.preventDefault();if(!image)return;const old=scale;scale=Math.max(.1,Math.min(20,scale*(e.deltaY<0?1.15:.87)));const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*canvas.width/r.width,y=(e.clientY-r.top)*canvas.height/r.height;ox=x-(x-ox)*scale/old;oy=y-(y-oy)*scale/old;draw();});
  const params=()=>Object.fromEntries(Object.entries(controls).map(([key,input])=>{if(input.dataset.numeric==="1"){const n=Number(input.value),s=SPECS[key];if(!Number.isFinite(n)||n<s.min||n>s.max||(s.odd&&n%2===0))throw new Error(t("ui.error.bge_parameter_range","Invalid value for {parameter}").replace("{parameter}",input.dataset.label));return[key,n];}return[key,input.type==="checkbox"?input.checked:input.value];}));
  async function request(requestView){const body={run_dir:runDir,params:params(),exclusion_polygons:polygons,view:requestView};const response=await fetch(api.httpUrl(API_ENDPOINTS.runs.bgePreview(runId)),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body),signal:controller.signal});if(!response.ok){const e=await response.json().catch(()=>({}));throw new Error(e?.error?.message||`HTTP ${response.status}`);}return response;}
  async function preview(){const current=++generation;controller?.abort();controller=new AbortController();status.textContent=t("ui.message.bge_loading","Calculating BGE preview…");status.style.color="var(--tc-danger,#ef4444)";const applyButton=document.querySelector("[data-bge-apply]");if(applyButton)applyButton.disabled=true;try{diag=await(await request("diagnostics")).json();const response=await request(view),blob=await response.blob(),url=URL.createObjectURL(blob),next=new Image();await new Promise((ok,no)=>{next.onload=ok;next.onerror=no;next.src=url;});URL.revokeObjectURL(url);if(current!==generation)return;image=next;fit();updateHistogram();const channels=(diag.channels||[]).map(c=>`${c.channel}: ${c.samples} / RMS ${Number(c.fit_rms||0).toPrecision(3)}`).join(" · ");info.textContent=`${t("ui.label.bge_source","Source")}: ${diag.source} · ${channels}`;if(diag.success){status.textContent=t("ui.message.bge_ready","BGE preview calculated.");status.style.color="var(--tc-success,#22c55e)";}else{status.textContent=t("ui.message.bge_guard_rejected","Preview calculated, but application was rejected by guards.");status.style.color="var(--tc-danger,#ef4444)";}if(applyButton)applyButton.disabled=!diag.success&&controls.apply_guards.checked;}catch(e){if(e.name!=="AbortError"&&current===generation)status.textContent=e.message;}}
  function schedule(){clearTimeout(timer);try{params();status.textContent="";timer=setTimeout(preview,400);}catch(e){status.textContent=e.message;status.style.color="var(--tc-danger,#ef4444)";}}
  async function switchView(v){view=v;controller?.abort();controller=new AbortController();try{const response=await request(view),blob=await response.blob(),url=URL.createObjectURL(blob),next=new Image();await new Promise((ok,no)=>{next.onload=ok;next.onerror=no;next.src=url;});URL.revokeObjectURL(url);image=next;fit();updateHistogram();}catch(e){if(e.name!=="AbortError")status.textContent=e.message;}}
  function field(key){const s=SPECS[key],label=t(`param.bge.autobge.${key}.label`,key),help=t(`param.bge.autobge.${key}.short_help`,"");let input;if(typeof s.value==="boolean")input=el("input",{type:"checkbox",checked:initial[key],onchange:schedule});else if(s.options)input=el("select",{class:"tc-select",onchange:schedule},...s.options.map(v=>el("option",{value:v,selected:initial[key]===v},t(`ui.option.bge_${v}`,v))));else input=el("input",{class:"tc-input",type:"number",value:initial[key],min:s.min,max:s.max,step:s.step,"data-numeric":"1","data-label":label,oninput:schedule,onchange:()=>{let n=Number(input.value);if(!Number.isFinite(n))n=initial[key];n=Math.min(s.max,Math.max(s.min,n));if(s.odd&&n%2===0)n=Math.min(s.max,n+1);input.value=n;schedule();}});input.title=help;controls[key]=input;return el("label",{class:"tc-flex-col tc-gap-1",title:help},el("span",{class:"tc-label tc-flex tc-gap-1"},label,el("span",{style:"cursor:help;opacity:.75",title:help},"ⓘ")),input);}
  const form=el("div",{class:"tc-grid-2 tc-gap-2"},...Object.keys(SPECS).map(field));
  const backdrop=el("div",{style:"position:fixed;inset:0;z-index:10000;background:rgba(0,0,0,.72);display:flex;align-items:center;justify-content:center;padding:16px"}),modal=el("div",{class:"tc-card",role:"dialog","aria-modal":"true",style:"width:min(1500px,96vw);max-height:95vh;overflow:auto"});
  const close=()=>{generation++;controller?.abort();clearTimeout(timer);backdrop.remove();};
  const apply=async()=>{const b=modal.querySelector("[data-bge-apply]");b.disabled=true;try{await onApply(patchBgeYaml(yaml,params(),polygons));close();}catch(e){status.textContent=e.message;b.disabled=false;}};
  const views=el("div",{class:"tc-flex tc-gap-2 tc-mb-2"},...[["original","ui.button.bge_original","Original"],["corrected","ui.button.bge_corrected","Corrected"],["background","ui.button.bge_background","Background"]].map(([v,k,f])=>el("button",{class:"tc-btn tc-btn-sm",onclick:()=>switchView(v)},t(k,f))));
  const modalChildren=[el("div",{class:"tc-card-title tc-flex tc-justify-between"},el("span",{},t("ui.title.bge_preview","Configure AutoBGE")),el("button",{class:"tc-btn tc-btn-sm",onclick:close},"×")),initial.method!=="autobge"?el("div",{class:"tc-card tc-mb-2"},t("ui.message.bge_switch_autobge","Applying this dialog switches bge.method to autobge.")):null,el("div",{style:"display:grid;grid-template-columns:minmax(0,2fr) minmax(340px,1fr);gap:16px"},el("div",{},views,canvas,el("div",{class:"tc-mt-2 tc-flex tc-gap-2 tc-flex-wrap"},el("button",{class:"tc-btn tc-btn-sm",onclick:()=>{drawMode=!drawMode;pending.splice(0);canvas.style.cursor=drawMode?"crosshair":"grab";}},t("ui.button.bge_draw_exclusion","Draw exclusion")),el("button",{class:"tc-btn tc-btn-sm",onclick:()=>{polygons.splice(0);pending.splice(0);draw();schedule();}},t("ui.button.bge_clear_exclusions","Clear exclusions"))),el("div",{class:"tc-mt-2 tc-flex tc-gap-3 tc-items-center tc-flex-wrap"},hist,info)),form),status,el("div",{class:"tc-mt-3 tc-flex tc-justify-between"},el("button",{class:"tc-btn",onclick:()=>{for(const[k,i]of Object.entries(controls)){if(i.type==="checkbox")i.checked=initial[k];else i.value=initial[k];}polygons.splice(0,...initialPolygons);pending.splice(0);schedule();}},t("ui.button.bge_reset","Reset")),el("div",{class:"tc-flex tc-gap-2"},el("button",{class:"tc-btn",onclick:close},t("ui.button.cancel","Cancel")),el("button",{class:"tc-btn tc-btn-primary","data-bge-apply":"1",onclick:apply},t("ui.button.bge_apply_resume","Apply & start resume"))))].filter(Boolean);modal.append(...modalChildren);backdrop.appendChild(modal);document.body.appendChild(backdrop);preview();
}
