pipeline:
  mode: production
  abort_on_fail: true
data:
  image_width: 3840
  image_height: 2160
  frames_min: 50
  color_mode: OSC
  bayer_pattern: GBRG
  linear_required: true
calibration:
  use_bias: false
  use_dark: true
  use_flat: false
  bias_use_master: false
  dark_use_master: true
  flat_use_master: false
  bias_dir: ''
  darks_dir: ''
  flats_dir: ''
  bias_master: ''
  dark_master: ''
  flat_master: ''
  pattern: '*.fit*'
assumptions:
  frames_min: 50
  frames_optimal: 200
  frames_reduced_threshold: 199
  exposure_time_tolerance_percent: 5.0
  warp_variance_warn: 2.0
  warp_variance_max: 8.0
  elongation_warn: 0.3
  elongation_max: 0.4
  reduced_mode_skip_clustering: true
  reduced_mode_cluster_range:
  - 5
  - 10
v4:
  iterations: 4
  beta: 6.0
  min_valid_tile_fraction: 0.3
  parallel_tiles: 8
  debug_tile_registration: false
  adaptive_tiles:
    enabled: true
    max_refine_passes: 4
    refine_variance_threshold: 0.1
    min_tile_size_px: 48
    use_warp_probe: true
    use_hierarchical: true
    initial_tile_size: 192
    probe_window: 256
    num_probe_frames: 5
    gradient_sensitivity: 2.0
    split_gradient_threshold: 0.3
    hierarchical_max_depth: 3
  convergence:
    enabled: false
    epsilon_rel: 0.001
  memory_limits:
    rss_warn_mb: 16384
    rss_abort_mb: 32768
  diagnostics:
    enabled: true
    warp_field: true
    tile_invalid_map: true
    warp_variance_hist: true
normalization:
  enabled: true
  mode: background
  per_channel: true
registration:
  mode: local_tiles
  local_tiles:
    max_warp_delta_px: 0.3
    ecc_cc_min: 0.35
    min_valid_frames: 3
    temporal_smoothing_window: 15
    variance_window_sigma: 2.0
wiener_denoise:
  enabled: true
  snr_threshold: 5.0
  q_min: -0.5
global_metrics:
  weights:
    background: 0.4
    noise: 0.3
    gradient: 0.3
  clamp:
  - -3
  - 3
tile:
  size_factor: 32
  min_size: 48
  max_divisor: 6
  overlap_fraction: 0.25
  star_min_count: 3
local_metrics:
  clamp:
  - -3
  - 3
  star_mode:
    weights:
      fwhm: 0.6
      roundness: 0.2
      contrast: 0.2
  structure_mode:
    background_weight: 0.3
    metric_weight: 0.7
linearity:
  enabled: true
  max_frames: 6
  min_overall_linearity: 0.75
  strictness: moderate
synthetic:
  weighting: tile_weighted
  frames_min: 3
  frames_max: 30
  clustering:
    mode: state_vector
    cluster_count_range:
    - 8
    - 12
    vector:
    - global_weight
    - tile_quality_mean
    - tile_quality_variance
    - background
    - noise
  auto_skip:
    enabled: true
    min_eligible_clusters: 2
    min_cluster_weight_spread: 0.05
    min_cluster_quality_spread: 0.2
reconstruction:
  weighting_function: exponential
  window_function: hanning
  tile_rescale: median_after_background_subtraction
debayer: true
stacking:
  method: rej
  input_dir: synthetic
  input_pattern: syn_*.fits
  output_file: stacked.fit
  sigma_clip:
    sigma_low: 2
    sigma_high: 2
    max_iters: 3
    min_fraction: 0.5
validation:
  min_fwhm_improvement_percent: 5
  max_background_rms_increase_percent: 0
  min_tile_weight_variance: 0.1
  require_no_tile_pattern: true
runtime_limits:
  tile_analysis_max_factor_vs_stack: 3.0
  hard_abort_hours: 6
