# =========================
# Allgemein
# =========================
run_dir: ./run
log_level: info   # trace | debug | info | warn | error

# =========================
# Data
# =========================
data:
  image_width: 3840
  image_height: 2160
  frames_min: 50
  color_mode: OSC
  bayer_pattern: GBRG
  linear_required: true

# =========================
# Pipeline
# =========================
pipeline:
  abort_on_fail: false
  phases:
    - scan_input
    - registration
    - done

# =========================
# Input
# =========================
input:
  pattern: "./data/*.fits"
  sort: numeric          # numeric | lexicographic
  max_frames: 0          # 0 = alle

# =========================
# Global Metrics
# =========================
global_metrics:
  enabled: true

  # Gewichtung der Qualitätskomponenten
  weights:
    background: 0.25
    noise: 0.45
    gradient_energy: 0.30

  # Clamping zur Robustheit gegen Ausreißer
  clamp:
    background: [0.0, 1.0]
    noise: [0.0, 1.0]
    gradient_energy: [0.0, 1.0]

# =========================
# Registrierung
# =========================
registration:
  enabled: true

  # Engine-Auswahl
  engine: star_similarity
  # engine: opencv_feature
  # engine: opencv_logpolar

  # Referenzwahl (nutzt global_metrics.json)
  reference_policy: global_weight
  # global_weight | quality_score | middle

  # Proxy / Downsampling
  downsample_factor: 2

  # Translation
  max_translation_px: 64

  # Rotation (nur wenn Engine es unterstützt)
  allow_rotation: false
  max_rotation_deg: 5.0

  # ECC-Refinement
  ecc:
    enabled: true
    iterations: 50
    epsilon: 1.0e-5

  # Robustheit
  min_score: 0.05
  fallback_to_identity: true

# =========================
# Output
# =========================
output:
  registered_dir: registered
  artifacts_dir: artifacts

  write_registered_frames: true
  write_global_metrics: true
  write_global_registration: true

