# Smart-Telescope Referenzkonfiguration (DWARF / ZWO Seestar)
# vollstaendig, alle Optionen; fuer OSC-Daten mit oft kuerzeren Einzelbelichtungen.

run_dir: ./run_smart_telescope
log_level: info # trace|debug|info|warn|error

pipeline:
  mode: production # production|test
  abort_on_fail: false # true => Lauf bei kritischem Phasenfehler sofort beenden

output:
  registered_dir: registered # Ausgabeordner fuer registrierte Frames
  artifacts_dir: artifacts # Ausgabeordner fuer JSON-Artefakte/Diagnosen
  write_registered_frames: true # registrierte Einzelbilder speichern
  write_global_metrics: true # global_metrics.json speichern
  write_global_registration: true # global_registration.json speichern

data:
  #image_width: 1920 # typische Smart-Telescope-Aufloesung, ggf. anpassen
  #image_height: 1080 # typische Smart-Telescope-Aufloesung, ggf. anpassen
  frames_min: 30 # Legacy-Mindestwert, parallel zu assumptions.frames_min
  frames_target: 0 # 0 = unbegrenzt, sonst Zielanzahl fuer Auswahl/Begrenzung
  #color_mode: OSC # Smart-Telescope ueblich: OSC
  #bayer_pattern: GBRG # je nach Sensor pruefen und ggf. ersetzen
  linear_required: true # nur lineare Daten verarbeiten

input:
  pattern: ./data/*.fits # Input-Glob fuer Rohframes
  sort: numeric # numeric|lexicographic
  max_frames: 0 # 0 = alle; >0 limitiert Inputanzahl

linearity:
  enabled: true # Linearity-Check aktiv
  max_frames: 8 # max. Frames fuer den Check
  min_overall_linearity: 0.9 # Mindestscore fuer linearity gate
  strictness: moderate # etwas toleranter bei Consumer-Sensoren

calibration:
  use_bias: false # Bias-Korrektur aktivieren
  use_dark: false # Dark-Korrektur aktivieren
  use_flat: false # Flat-Korrektur aktivieren
  bias_use_master: false # vorhandenes Master-Bias direkt nutzen
  dark_use_master: false # vorhandenes Master-Dark direkt nutzen
  flat_use_master: false # vorhandenes Master-Flat direkt nutzen
  dark_auto_select: true # passendes Dark automatisch waehlen
  dark_match_exposure_tolerance_percent: 8.0 # Smart-Telescope oft variablere Sequenzen
  dark_match_use_temp: false # Temperaturmatching optional
  dark_match_temp_tolerance_c: 3.0 # Temperaturtoleranz in Grad C
  bias_dir: "" # Verzeichnis mit Bias-Frames
  darks_dir: "" # Verzeichnis mit Dark-Frames
  flats_dir: "" # Verzeichnis mit Flat-Frames
  bias_master: "" # Pfad zu Master-Bias
  dark_master: "" # Pfad zu Master-Dark
  flat_master: "" # Pfad zu Master-Flat
  pattern: "*.fit*" # Dateimaske fuer Kalibrierdaten

assumptions:
  frames_min: 30 # niedrigere Untergrenze fuer kurze Smart-Telescope-Serien
  frames_optimal: 300 # praxisnahes Ziel fuer portable Systeme
  frames_reduced_threshold: 120 # Full-Mode ab 120, darunter Reduced/Emergency
  exposure_time_tolerance_percent: 8.0 # toleranter fuer variierende Sub-Serien
  reduced_mode_skip_clustering: true # kleine Datensaetze: Clustering oft nicht stabil
  reduced_mode_cluster_range: [3, 10] # geringere Clusterzahl fuer kleinere N

normalization:
  enabled: true # fuer Methodik v3.x verpflichtend
  mode: background # background|median
  per_channel: true # bei OSC pro Bayer-Kanal normalisieren

registration:
  # Temporal-Smoothing (v3.2.3+): Automatisch aktiv bei Feldrotation
  # - Nutzt Nachbar-Frames (i-1, i+1) wenn direkte Registrierung fehlschlaegt
  # - Verkettete Warps: i→(i-1)→ref oder i→(i+1)→ref
  # Adaptive Stern-Detektion: Automatischer Fallback auf 2.5σ bei wenigen Sternen
  
  engine: triangle_star_matching # triangle_star_matching|star_similarity|hybrid_phase_ecc|robust_phase_ecc
  allow_rotation: true # Rotationsanteil in Warp erlauben
  star_topk: 100 # leicht reduziert fuer kompaktere Felder
  star_min_inliers: 4 # Mindestzahl Inlier fuer Stern-Matching
  star_inlier_tol_px: 3.0 # Inlier-Toleranz in Pixel
  star_dist_bin_px: 5.0 # Distanz-Binning fuer Sternpaare
  reject_outliers: true # globale Registrierungs-Ausreisser verwerfen
  reject_cc_min_abs: 0.35 # absolute Mindestkorrelation (CC)
  reject_cc_mad_multiplier: 4.0 # robuster CC-Schwellenfaktor (median - k*MAD)
  reject_shift_px_min: 25.0 # absolute Mindestgrenze fuer Shift-Outlier (px)
  reject_shift_median_multiplier: 3.0 # Shift-Outlier-Grenze relativ zum Median
  reject_scale_min: 0.92 # minimale erlaubte Similarity-Skalierung
  reject_scale_max: 1.08 # maximale erlaubte Similarity-Skalierung

dithering:
  enabled: true # Smart-Telescope Session typischerweise mit Dithering
  min_shift_px: 0.7 # Schwellwert fuer Dither-Erkennung in Pixeln

tile_denoise:
  soft_threshold:
    enabled: true # Highpass + Soft-Threshold pro Tile
    blur_kernel: 21 # kleiner Kernel fuer kompaktere Aufloesungen
    alpha: 1.6 # moderates Denoising
    skip_star_tiles: true # sternreiche Tiles vom Denoise ausnehmen
  wiener:
    enabled: true # Wiener-Denoise im Frequenzraum
    snr_threshold: 4.0 # etwas frueher aktiv bei rauschigeren Smart-Sensoren
    q_min: -0.5 # untere Strukturqualitaetsgrenze
    q_max: 1.0 # obere Strukturqualitaetsgrenze
    q_step: 0.1 # Schrittweite in q-Optimierung
    min_snr: 2.0 # minimaler SNR fuer stabile Schaetzung
    max_iterations: 10 # Iterationslimit der Wiener-Optimierung

chroma_denoise:
  enabled: true # Farbrausch-Reduktion fuer OSC-Daten
  color_space: ycbcr_linear # ycbcr_linear|opponent_linear
  apply_stage: post_stack_linear # pre_stack_tiles|post_stack_linear
  protect_luma: true # Luma/Struktur besser erhalten
  luma_guard_strength: 0.75 # 0..1
  star_protection:
    enabled: true
    threshold_sigma: 2.2
    dilate_px: 2
  structure_protection:
    enabled: true
    gradient_percentile: 85
  chroma_wavelet:
    enabled: true
    levels: 3
    threshold_scale: 1.0
    soft_k: 1.0
  chroma_bilateral:
    enabled: true
    sigma_spatial: 1.2
    sigma_range: 0.025
  blend:
    mode: chroma_only
    amount: 0.7
  # Preset-Hinweis:
  # conservative: amount 0.65, threshold_scale 1.0, sigma_range 0.025
  # balanced:     amount 0.85, threshold_scale 1.25, sigma_range 0.035
  # aggressive:   amount 0.95, threshold_scale 1.5, sigma_range 0.05

global_metrics:
  adaptive_weights: true # adaptive Gewichtung nach Metrikvarianz
  weight_exponent_scale: 1.4 # geringere Spreizung fuer heterogene Smart-Frames
  weights:
    background: 0.45 # etwas mehr Gewicht auf gleichmaessigen Hintergrund
    noise: 0.35 # leicht erhoehtes Rauschgewicht
    gradient: 0.20 # etwas weniger Fokus auf Gradientenergie
  clamp: [-3.0, 3.0] # Clipping-Grenzen fuer z-Score-Metriken

tile:
  size_factor: 24 # kleinere Tiles fuer typische Smart-Telescope-Aufloesungen
  min_size: 48 # minimale Tilekante in Pixel
  max_divisor: 6 # Begrenzung der Tileunterteilung
  overlap_fraction: 0.25 # OLA-Ueberlappungsanteil
  star_min_count: 6 # geringere Sternzahl-Schwelle in kleinen Feldern

local_metrics:
  clamp: [-3.0, 3.0] # Clipping fuer lokale z-Score-Metriken
  star_mode:
    weights:
      fwhm: 0.6 # Gewicht Stern-FWHM
      roundness: 0.2 # Gewicht Sternrundheit
      contrast: 0.2 # Gewicht Sternkontrast
  structure_mode:
    metric_weight: 0.7 # Gewicht Strukturmetrik
    background_weight: 0.3 # Gewicht lokaler Hintergrundterm

synthetic:
  weighting: tile_weighted # global|tile_weighted
  frames_min: 4 # kleinere Cluster tolerieren
  frames_max: 20 # Synthetic-Anzahl begrenzen
  clustering:
    mode: kmeans # kmeans|quantile
    cluster_count_range: [3, 12] # [k_min, k_max] fuer kleinere Datensaetze

reconstruction:
  weighting_function: linear # aktuell linear
  window_function: hanning # OLA-Fensterfunktion

debayer: true # OSC-Mosaik am Ende in RGB debayern

astrometry:
  enabled: true # WCS-Solve aktiv
  astap_bin: "" # leer => Systempfad
  astap_data_dir: /media/data/Astro/astap # ASTAP-Datenverzeichnis
  search_radius: 183 # Suchradius in Grad

pcc:
  enabled: true # Photometrische Farbkalibrierung aktiv
  source: siril # auto|siril|vizier_gaia|vizier_apass
  mag_limit: 14 # maximal beruecksichtigte Sternhelligkeit
  mag_bright_limit: 6 # helle Sterne fuer robustes Fit begrenzen
  aperture_radius_px: 8 # Photometrie-Apertur
  annulus_inner_px: 10 # Hintergrundring innen
  annulus_outer_px: 16 # Hintergrundring aussen
  min_stars: 3 # Mindestanzahl Referenzsterne
  sigma_clip: 2.5 # Sigma-Clipping fuer Regressionsfit
  siril_catalog_dir: "" # leer => Standardkatalogpfad

stacking:
  method: rej # rej|average
  sigma_clip:
    sigma_low: 2.0 # untere Sigma-Grenze
    sigma_high: 2.0 # obere Sigma-Grenze
    max_iters: 3 # maximale Clip-Iterationen
    min_fraction: 0.5 # Mindestanteil verbleibender Samples
  cluster_quality_weighting:
    enabled: true # v3.2.2: finale Clusteraggregation gewichtet mit w_k=exp(kappa_cluster*Q_k)
    kappa_cluster: 1.0 # Exponent fuer Clusterqualitaet (Q_k in [-3,+3])
    cap_enabled: false # optionales Dominanz-Cap fuer einzelne Clustergewichte
    cap_ratio: 20.0 # nur aktiv falls cap_enabled=true: w_k <= cap_ratio * median(w)
  output_stretch: false # optionales Display-Stretch (Post)
  cosmetic_correction: false # optionale Kosmetik (Post)
  cosmetic_correction_sigma: 10.0  # konservativ: nur echte Hot Pixel (sigma=3 wuerde Galaxienkerne zerstoeren)

validation:
  min_fwhm_improvement_percent: 3.0 # etwas realistischere Schwelle fuer kompakte Systeme
  max_background_rms_increase_percent: 2.0 # leichte RMS-Zunahme tolerieren
  min_tile_weight_variance: 0.05 # geringere Varianzschwelle fuer kleine N
  require_no_tile_pattern: true # Grid-Artefakte muessen ausbleiben

runtime_limits:
  parallel_workers: 8 # Anzahl paralleler Worker fuer Tile-Phasen (CPU/memory capped)
  memory_budget: 2048 # MiB Budget fuer OSC-Worker-Cap in Tile-Rekonstruktion
  tile_analysis_max_factor_vs_stack: 3.0 # Guardrail Laufzeit Tile-Analyse
  hard_abort_hours: 6.0 # harte Laufzeitgrenze
  allow_emergency_mode: true # portable Sessions oft kurz => Emergency erlauben
